# Generated by Django 5.0.2 on 2025-04-21 08:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='邮箱地址')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('avatar', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('ban_reason', models.TextField(blank=True, max_length=500, null=True, verbose_name='封禁原因')),
                ('ban_until', models.DateTimeField(blank=True, null=True, verbose_name='封禁截止时间')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='关注')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
    ]
