# Generated by Django 5.0.2 on 2025-04-11 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_user_avatar_user_ban_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='智能体名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agents', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '智能体',
                'verbose_name_plural': '智能体',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', '通过'), ('reject', '拒绝')], max_length=20, verbose_name='审核决定')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核员')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.aiagent', verbose_name='智能体')),
            ],
            options={
                'verbose_name': '智能体审核记录',
                'verbose_name_plural': '智能体审核记录',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create_agent', '创建智能体'), ('edit_agent', '编辑智能体'), ('delete_agent', '删除智能体'), ('follow', '关注用户'), ('unfollow', '取消关注')], max_length=50, verbose_name='行为类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('target_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为日志',
                'verbose_name_plural': '用户行为日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
