# Generated by Django 5.0.2 on 2025-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_options_user_avatar_user_ban_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=30, verbose_name="用户名"),
        ),
    ]
